include:
- compose-base.yaml

services:
  ship-app:
    extends:
      file: compose.yaml
      service: ship-app
    depends_on:
    - ship-redis-storage

  ship-redis-storage:
    extends:
      file: compose.yaml
      service: ship-redis-storage
    volumes:
    - ship-redis-api-test-data:/data
    - ./redis-storage/redis.conf:/usr/local/etc/redis/redis.conf

  ship-redis-populator:
    extends:
      file: compose.yaml
      service: ship-redis-populator
    entrypoint: ["sh", "/redis-populator/populate.sh", "/redis-populator/api-test-data.txt"]
    depends_on:
    - ship-redis-storage

volumes:
  ship-redis-api-test-data:
    labels:
    - "app-identity=delivery-magic"
    - "app-volume=ship-redis-api-test-data"
