include:
- compose-base.yaml

services:
  app:
    extends:
      file: compose.yaml
      service: app
    depends_on:
    - redis-storage

  redis-storage:
    extends:
      file: compose.yaml
      service: redis-storage
    volumes:
    - redis-api-test-data:/data
    - ./redis-storage/redis.conf:/usr/local/etc/redis/redis.conf

  redis-populator:
    extends:
      file: compose.yaml
      service: redis-populator
    entrypoint: ["sh", "/redis-populator/populate.sh", "/redis-populator/api-test-data.txt"]
    depends_on:
    - redis-storage

volumes:
  redis-api-test-data:
    labels:
    - "app-identity=delivery-magic"
    - "app-volume=ship-redis-api-test-data"
