include:
  - compose-base.yaml

name: md-ship

services:
  app:
    annotations:
      com.chillysoftware.md.ship.app.lang: go
    build:
      context: ../..
      dockerfile: ./deploy/docker/app/Dockerfile
    container_name: md-ship-app
    depends_on:
      redis-storage:
        condition: service_healthy
    env_file:
      - path: "./.env"
        required: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      - "app-identity=magic-delivery"
      - "app-service=md-ship-app"
    networks:
      - public
      - redis
      - md-pl-public
    ports:
      - "8080:8080/tcp"
    read_only: true
    restart: unless-stopped

  redis-storage:
    container_name: md-ship-redis-storage
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 1s
    image: redis
    labels:
      - "app-identity=magic-delivery"
      - "app-service=md-ship-redis-storage"
    networks:
      - redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
      - ./redis-storage/redis.conf:/usr/local/etc/redis/redis.conf

  redis-populator:
    container_name: md-ship-redis-populator
    depends_on:
      - redis-storage
    entrypoint: ["bash", "/redis-populator/populate.sh", "/redis-populator/data.txt"]
    env_file:
      - ./.env
    image: redis
    labels:
      - "app-identity=magic-delivery"
      - "app-service=md-ship-redis-populator"
    networks:
      - redis
    volumes:
      - ./redis-populator:/redis-populator
    read_only: true

  redis-backup:
    container_name: md-ship-redis-backup
    depends_on:
      - redis-storage
    entrypoint: ["/snapshot-backup.sh"]
    environment:
      - BACKUP_PERIOD=10
    image: bash
    network_mode: "none"
    restart: unless-stopped
    volumes:
      - ./redis-backup/snapshot-backup.sh:/snapshot-backup.sh
      - redis-data:/data:ro
      - backup:/backup

volumes:
  backup:
    name: md-ship-backup
    labels:
      - "app-identity=magic-delivery"
      - "app-volume=md-ship-backup"
  redis-data:
    name: md-ship-redis-data
    labels:
      - "app-identity=magic-delivery"
      - "app-volume=md-ship-redis-data"
