// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CustomerDeleter is an autogenerated mock type for the CustomerDeleter type
type CustomerDeleter struct {
	mock.Mock
}

// DeleteCustomer provides a mock function with given fields: ctx, id
func (_m *CustomerDeleter) DeleteCustomer(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCustomer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCustomerDeleter creates a new instance of CustomerDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerDeleter {
	mock := &CustomerDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
