on:
  push:
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'internal/**'
jobs:
  test:
    name: Test the 'Shipping' service
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up go 1.x
      uses: actions/setup-go@v5.0.2
      with:
        go-version: ^1.22

    - name: Check out code into the Go module directory 
      uses: actions/checkout@v4.1.7
     
    - name: Run Test
      run: make test

    - name: Coverage percentage threshold check
      run: make check-coverage-threshold

    # - name: Generate HTML coverage report
    #   run: make report

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v4

    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: ./deploy/docker/app/Dockerfile
        push: true
        tags: tnsoftbear/md-ship-app:latest


  # build:
  #   name: Build the 'Shipping' service
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up go 1.x
  #       uses: actions/setup-go@v5.0.2
  #       with:
  #         go-version: ^1.22

  #     - name: Check out code into the Go module directory 
  #       uses: actions/checkout@v4.1.7

  #     - name: Build
  #       run: go build -o shipping_service ./cmd/shipping_service.go