on:
  push:
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'internal/**'
jobs:
  test:
    name: Test the 'Shipping' service
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up go 1.x
      uses: actions/setup-go@v5.0.2
      with:
        go-version: ^1.22

    - name: Check out code into the Go module directory 
      uses: actions/checkout@v4.1.7
     
    - name: Run Test
      run: make test

    - name: Coverage percentage threshold check
      run: make check-coverage-threshold

    # - name: Generate HTML coverage report
    #   run: make report

  # build:
  #   name: Build the 'Shipping' service
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up go 1.x
  #       uses: actions/setup-go@v5.0.2
  #       with:
  #         go-version: ^1.22

  #     - name: Check out code into the Go module directory 
  #       uses: actions/checkout@v4.1.7

  #     - name: Build
  #       run: go build -o shipping_service ./cmd/shipping_service.go