name: unit-testing

on:
  push:
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'internal/**'
  pull_request:
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'internal/**'
  
jobs:
  run-tests:
    name: Test the 'Shipping' service
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up go 1.x
      uses: actions/setup-go@v5.0.2
      with:
        go-version: ^1.22

    - name: Check out code into the Go module directory 
      uses: actions/checkout@v4.1.7
     
    - name: Run Test
      id: run-unit-tests
      run: make test

    - name: Coverage percentage threshold check
      run: make check-coverage-threshold
